//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalTrainer.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalTrainer.Resx.AppResource", typeof(AppResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Training.
        /// </summary>
        internal static string AddTraining {
            get {
                return ResourceManager.GetString("AddTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketball.
        /// </summary>
        internal static string Basketball {
            get {
                return ResourceManager.GetString("Basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi1.
        /// </summary>
        internal static string Bmi1 {
            get {
                return ResourceManager.GetString("Bmi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi2.
        /// </summary>
        internal static string Bmi2 {
            get {
                return ResourceManager.GetString("Bmi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi3.
        /// </summary>
        internal static string Bmi3 {
            get {
                return ResourceManager.GetString("Bmi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi4.
        /// </summary>
        internal static string Bmi4 {
            get {
                return ResourceManager.GetString("Bmi4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi5.
        /// </summary>
        internal static string Bmi5 {
            get {
                return ResourceManager.GetString("Bmi5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi6.
        /// </summary>
        internal static string Bmi6 {
            get {
                return ResourceManager.GetString("Bmi6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi7.
        /// </summary>
        internal static string Bmi7 {
            get {
                return ResourceManager.GetString("Bmi7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmi8.
        /// </summary>
        internal static string Bmi8 {
            get {
                return ResourceManager.GetString("Bmi8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI weight is:.
        /// </summary>
        internal static string BMIis {
            get {
                return ResourceManager.GetString("BMIis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        internal static string BMIlbl {
            get {
                return ResourceManager.GetString("BMIlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a calendar with a custom style..
        /// </summary>
        internal static string CustomAppearanceDescription {
            get {
                return ResourceManager.GetString("CustomAppearanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Appearance.
        /// </summary>
        internal static string CustomAppearanceTitle {
            get {
                return ResourceManager.GetString("CustomAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to customize a day slot to show custom content..
        /// </summary>
        internal static string CustomDayContentDescription {
            get {
                return ResourceManager.GetString("CustomDayContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Day Content.
        /// </summary>
        internal static string CustomDayContentTitle {
            get {
                return ResourceManager.GetString("CustomDayContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a custom header inspired by a popular Android or iOS calendar app..
        /// </summary>
        internal static string CustomHeaderDescription {
            get {
                return ResourceManager.GetString("CustomHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Header.
        /// </summary>
        internal static string CustomHeaderTitle {
            get {
                return ResourceManager.GetString("CustomHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows custom selection scenarios..
        /// </summary>
        internal static string CustomSelectionDescription {
            get {
                return ResourceManager.GetString("CustomSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Select a date
        ///Step 2: Select another date in a different week
        ///Observe: The weekend days are not selected.
        /// </summary>
        internal static string CustomSelectionMessage {
            get {
                return ResourceManager.GetString("CustomSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Selection.
        /// </summary>
        internal static string CustomSelectionTitle {
            get {
                return ResourceManager.GetString("CustomSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycling.
        /// </summary>
        internal static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date starded.
        /// </summary>
        internal static string DateStarded {
            get {
                return ResourceManager.GetString("DateStarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decade.
        /// </summary>
        internal static string DecadeLabel {
            get {
                return ResourceManager.GetString("DecadeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famale.
        /// </summary>
        internal static string Famale {
            get {
                return ResourceManager.GetString("Famale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football.
        /// </summary>
        internal static string Football {
            get {
                return ResourceManager.GetString("Football", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a basic calendar with selection and interaction..
        /// </summary>
        internal static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        internal static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        internal static string Gym {
            get {
                return ResourceManager.GetString("Gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mane.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MonthLabel {
            get {
                return ResourceManager.GetString("MonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalTrener.
        /// </summary>
        internal static string PersonalTrener {
            get {
                return ResourceManager.GetString("PersonalTrener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a date.
        /// </summary>
        internal static string PickDateLabel {
            get {
                return ResourceManager.GetString("PickDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use the control as a pop-up date selector..
        /// </summary>
        internal static string PopupEditorDescription {
            get {
                return ResourceManager.GetString("PopupEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Editor.
        /// </summary>
        internal static string PopupEditorTitle {
            get {
                return ResourceManager.GetString("PopupEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveChanges.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date {0:d} was selected..
        /// </summary>
        internal static string SelectedDateMessage {
            get {
                return ResourceManager.GetString("SelectedDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport type.
        /// </summary>
        internal static string SportType {
            get {
                return ResourceManager.GetString("SportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Calendar.
        /// </summary>
        internal static string TrainingCalendar {
            get {
                return ResourceManager.GetString("TrainingCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training length time (min).
        /// </summary>
        internal static string TrainingLengthMin {
            get {
                return ResourceManager.GetString("TrainingLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user info.
        /// </summary>
        internal static string UserEditInfo {
            get {
                return ResourceManager.GetString("UserEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a calendar with vertical navigation/scrolling..
        /// </summary>
        internal static string VerticalOrientationDescription {
            get {
                return ResourceManager.GetString("VerticalOrientationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Orientation.
        /// </summary>
        internal static string VerticalOrientationTitle {
            get {
                return ResourceManager.GetString("VerticalOrientationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YearLabel {
            get {
                return ResourceManager.GetString("YearLabel", resourceCulture);
            }
        }
    }
}
